name: NFTMC-Core
version: '${project.version}'
main: io.nftmc.nftmccore.NFTMCCore
api-version: 1.17

commands:
  view:
    description: Visits an NFT.
    usage: /v <NFTMC ID>
    aliases: [nft, v, view, check, c]
    permission: nftmc.view
  viewrandom:
    description: Visits a random NFT.
    usage: /vr
    aliases: [viewrandom, vr, nftr, checkrandom, cr]
    permission: nftmc.viewrandom
  help:
    description: Lists available commands.
    usage: /help
    permission: nftmc.help